export default [
    { value: 'ALABAMA', key: 'AL' },
    { value: 'ALASKA', key: 'AK' },
    { value: 'AMERICAN SAMOA', key: 'AS' },
    { value: 'ARIZONA', key: 'AZ' },
    { value: 'ARKANSAS', key: 'AR' },
    { value: 'CALIFORNIA', key: 'CA' },
    { value: 'COLORADO', key: 'CO' },
    { value: 'CONNECTICUT', key: 'CT' },
    { value: 'DELAWARE', key: 'DE' },
    { value: 'DISTRICT OF COLUMBIA', key: 'DC' },
    { value: 'FEDERATED STATES OF MICRONESIA', key: 'FM' },
    { value: 'FLORIDA', key: 'FL' },
    { value: 'GEORGIA', key: 'GA' },
    { value: 'GUAM', key: 'GU' },
    { value: 'HAWAII', key: 'HI' },
    { value: 'IDAHO', key: 'ID' },
    { value: 'ILLINOIS', key: 'IL' },
    { value: 'INDIANA', key: 'IN' },
    { value: 'IOWA', key: 'IA' },
    { value: 'KANSAS', key: 'KS' },
    { value: 'KENTUCKY', key: 'KY' },
    { value: 'LOUISIANA', key: 'LA' },
    { value: 'MAINE', key: 'ME' },
    { value: 'MARSHALL ISLANDS', key: 'MH' },
    { value: 'MARYLAND', key: 'MD' },
    { value: 'MASSACHUSETTS', key: 'MA' },
    { value: 'MICHIGAN', key: 'MI' },
    { value: 'MINNESOTA', key: 'MN' },
    { value: 'MISSISSIPPI', key: 'MS' },
    { value: 'MISSOURI', key: 'MO' },
    { value: 'MONTANA', key: 'MT' },
    { value: 'NEBRASKA', key: 'NE' },
    { value: 'NEVADA', key: 'NV' },
    { value: 'NEW HAMPSHIRE', key: 'NH' },
    { value: 'NEW JERSEY', key: 'NJ' },
    { value: 'NEW MEXICO', key: 'NM' },
    { value: 'NEW YORK', key: 'NY' },
    { value: 'NORTH CAROLINA', key: 'NC' },
    { value: 'NORTH DAKOTA', key: 'ND' },
    { value: 'NORTHERN MARIANA ISLANDS', key: 'MP' },
    { value: 'OHIO', key: 'OH' },
    { value: 'OKLAHOMA', key: 'OK' },
    { value: 'OREGON', key: 'OR' },
    { value: 'PALAU', key: 'PW' },
    { value: 'PENNSYLVANIA', key: 'PA' },
    { value: 'PUERTO RICO', key: 'PR' },
    { value: 'RHODE ISLAND', key: 'RI' },
    { value: 'SOUTH CAROLINA', key: 'SC' },
    { value: 'SOUTH DAKOTA', key: 'SD' },
    { value: 'TENNESSEE', key: 'TN' },
    { value: 'TEXAS', key: 'TX' },
    { value: 'UTAH', key: 'UT' },
    { value: 'VERMONT', key: 'VT' },
    { value: 'VIRGIN ISLANDS', key: 'VI' },
    { value: 'VIRGINIA', key: 'VA' },
    { value: 'WASHINGTON', key: 'WA' },
    { value: 'WEST VIRGINIA', key: 'WV' },
    { value: 'WISCONSIN', key: 'WI' },
    { value: 'WYOMING', key: 'WY' },
];
